Fix to allow SiteMesh to run on Google AppEngine: - catch NoClassDefFoundError which is caused by attempting to use JNDI.
Thanks to Robert Hanson.

Reviewed by: